### ISSUE TITLE
Can estab run on Windows operating system?

### ISSUE THREAD

**Issue by leechuen** [miku/estab#1]
Hi,
Can estab run on Windows platform?

**Comment by miku** [comment]
Yes it will run. But there are no windows binaries or packages at the moment.

You can install Go on [Windows](http://golang.org/doc/install#windows) and compile a binary, or [cross-compile](https://github.com/golang/go/wiki/WindowsCrossCompiling) a Windows binary on Linux.

**Comment by miku** [comment]
May I ask you to open another issue for more specific windows problems? Meanwhile I close this.
