### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by eperdeme** [miku/estab#4]
Hello,

Do you have any example of what format you are supposed to put with -query ?

**Comment by miku** [comment]
It's the usual [query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html) syntax:

```
$ estab -indices test -query '{"query": {"match_all": {}}}'
AUpc1pzafTPRSR-BvA4z    test
AUpc1rSafTPRSR-BvA40    test
AUpc1svbfTPRSR-BvA41    test
```

I will update the README shortly.

**Comment by eperdeme** [comment]
Looks good to me.

So the below example works for me

 -query '{"query": { "filtered": { "query": { "query_string": { "query": "applicationEvent:\"CREDIT_ADDED\"" }}}}}'
